import PublicMenu from '@/components/menu/PublicMenu'

const DEMO_MENU = {
  id: 'demo',
  restaurant_name: 'Արաքս Սրճարան',
  logo_url: null,
  primary_color: '#4f8ef7',
}

const DEMO_CATEGORIES = [
  {
    id: 'cat-1',
    name_ru: 'Горячие блюда',
    name_hy: 'Տաք ուտեստներ',
    name_en: 'Hot dishes',
    position: 0,
    items: [
      {
        id: 'item-1',
        category_id: 'cat-1',
        name_ru: 'Хаш',
        name_hy: 'Խաշ',
        name_en: 'Khash',
        description_ru: 'Традиционный армянский суп из говяжьих ног, подаётся с лавашом и чесноком.',
        description_hy: 'Ավանդական հայկական ապուր տավարի ոտքերից, մատուցվում է լավաշով և սխտորով։',
        description_en: 'Traditional Armenian soup made from beef feet, served with lavash and garlic.',
        price: 2500,
        currency: 'AMD',
        image_url: '/demo/khash.jpg',
        is_available: true,
        position: 0,
      },
      {
        id: 'item-2',
        category_id: 'cat-1',
        name_ru: 'Долма',
        name_hy: 'Դոլմա',
        name_en: 'Dolma',
        description_ru: 'Виноградные листья, фаршированные рисом и мясом со специями.',
        description_hy: 'Խաղողի տերեւներ՝ լցված բրնձով և մսով՝ համեմունքներով։',
        description_en: 'Grape leaves stuffed with spiced rice and minced meat.',
        price: 3200,
        currency: 'AMD',
        image_url: '/demo/dolma.jpg',
        is_available: true,
        position: 1,
      },
      {
        id: 'item-3',
        category_id: 'cat-1',
        name_ru: 'Кюфта',
        name_hy: 'Կյուֆթա',
        name_en: 'Kyufta',
        description_ru: 'Армянские мясные шарики из говядины с маслом и яйцом.',
        description_hy: 'Հայկական մսի գնդիկներ տավարի մսից՝ կարագով և ձվով։',
        description_en: 'Armenian beef meatballs with butter and egg.',
        price: 3800,
        currency: 'AMD',
        image_url: '/demo/kyufta.jpg',
        is_available: false,
        position: 2,
      },
    ],
  },
  {
    id: 'cat-2',
    name_ru: 'Салаты',
    name_hy: 'Աղցաններ',
    name_en: 'Salads',
    position: 1,
    items: [
      {
        id: 'item-4',
        category_id: 'cat-2',
        name_ru: 'Летний салат',
        name_hy: 'Ամառային աղցան',
        name_en: 'Summer salad',
        description_ru: 'Свежие помидоры, огурцы, перец и зелень с оливковым маслом.',
        description_hy: 'Թարմ լոլիկ, վարունգ, պղպեղ և կանաչեղեն ձիթապտղի յուղով։',
        description_en: 'Fresh tomatoes, cucumbers, peppers and herbs with olive oil.',
        price: 1800,
        currency: 'AMD',
        image_url: '/demo/salad-summer.jpg',
        is_available: true,
        position: 0,
      },
      {
        id: 'item-5',
        category_id: 'cat-2',
        name_ru: 'Салат с сыром',
        name_hy: 'Պանրով աղցան',
        name_en: 'Cheese salad',
        description_ru: 'Микс зелени с домашним сыром, орехами и гранатом.',
        description_hy: 'Կանաչեղենի միքս՝ տնական պանրով, ընկույզով և նռնով։',
        description_en: 'Greens mix with homemade cheese, walnuts and pomegranate.',
        price: 2200,
        currency: 'AMD',
        image_url: '/demo/salad-cheese.jpg',
        is_available: true,
        position: 1,
      },
    ],
  },
  {
    id: 'cat-3',
    name_ru: 'Напитки',
    name_hy: 'Ըմպելիքներ',
    name_en: 'Drinks',
    position: 2,
    items: [
      {
        id: 'item-6',
        category_id: 'cat-3',
        name_ru: 'Армянский кофе',
        name_hy: 'Հայկական սուրճ',
        name_en: 'Armenian coffee',
        description_ru: 'Крепкий кофе по-армянски, сваренный в джезве.',
        description_hy: 'Հայկական ուժեղ սուրճ՝ պատրաստված ջեզվեում։',
        description_en: 'Strong Armenian-style coffee brewed in a cezve.',
        price: 800,
        currency: 'AMD',
        image_url: '/demo/coffee.jpg',
        is_available: true,
        position: 0,
      },
      {
        id: 'item-7',
        category_id: 'cat-3',
        name_ru: 'Тан',
        name_hy: 'Թան',
        name_en: 'Tan',
        description_ru: 'Освежающий кисломолочный напиток с газом.',
        description_hy: 'Թարմացնող թթվասեր խմիչք գազով։',
        description_en: 'Refreshing sparkling fermented milk drink.',
        price: 600,
        currency: 'AMD',
        image_url: '/demo/tan.jpg',
        is_available: true,
        position: 1,
      },
      {
        id: 'item-8',
        category_id: 'cat-3',
        name_ru: 'Гранатовый сок',
        name_hy: 'Նռան հյութ',
        name_en: 'Pomegranate juice',
        description_ru: 'Свежевыжатый сок из армянского граната.',
        description_hy: 'Թարմ սեղմված հյութ հայկական նռից։',
        description_en: 'Freshly squeezed juice from Armenian pomegranate.',
        price: 1200,
        currency: 'AMD',
        image_url: '/demo/pomegranate-juice.jpg',
        is_available: true,
        position: 2,
      },
    ],
  },
]

export default function DemoMenuPage() {
  return <PublicMenu menu={DEMO_MENU} categories={DEMO_CATEGORIES} isDemo />
}
